// Crea un usuario
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Admin22",
    "email": "admin2@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
// Get para todos los usuarios
GET http://localhost:5000/users

###
// Get Single user
GET http://localhost:5000/users/8262c91e-f985-4eae-81c2-6557e0faadc3

###
// Actualizar usuario
PATCH  http://localhost:5000/users/8262c91e-f985-4eae-81c2-6557e0faadc3
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
// Eliminar usuario
DELETE  http://localhost:5000/users/8262c91e-f985-4eae-81c2-6557e0faadc3

###
// Login admin
POST http://localhost:5000/login
Content-Type: application/json

{   
    "email": "admin@gmail.com",
    "password": "123456"    
}

###
//Login usuario 
POST http://localhost:5000/login
Content-Type: application/json

{   
    "email": "john@gmail.com",
    "password": "123456"    
}

###
// Get usuario logueado
GET http://localhost:5000/me

###
// Logout usuario
DELETE http://localhost:5000/logout 

###
// Get para todos los productos
GET http://localhost:5000/products

###
// Get Single producto
GET http://localhost:5000/products/aa4efa9a-a240-4dc5-869f-5efeff261a72

###
// Post Data Product crear producto
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Producto 1", 
    "price": 999,
    "description": "Producto 1 creado",
    "available": "yes"
}

###
// Patch Update Product
PATCH http://localhost:5000/products/aa4efa9a-a240-4dc5-869f-5efeff261a72
Content-Type: application/json

{
    "name": "Producto 1 actualizado", 
    "price": 999999,
    "description": "es un bonito producto pero ya no esta disponible para la venta",
    "available": "no"
}

###
// Eliminar producto
DELETE http://localhost:5000/products/aa4efa9a-a240-4dc5-869f-5efeff261a72

###
// Creacion de formularios
POST http://localhost:5000/forms
Content-Type: application/json

{
    "nameForm": "formulario 1 creado",
    "nameUser": "Juan",
    "nameUser2" : "Malo",
    "lastnameone": "Perez",
    "lastnametwo": "Sanchez",
    "birthday": "20 de noviembre",
    "category1": "infantil SC",
    "typekit": "Kit asociacion",
    "talla": "M",
    "team": "garzas",
    "phone": "1234567890",
    "email": "leo@gmail.com",
    "origin": "Teotihuacan"
}

###
// Get para todos los formularios
GET http://localhost:5000/forms

###
// Get para actualizar el formulario
PATCH http://localhost:5000/forms/8225ec4d-f2a2-45b5-9b30-c81c58833d54
Content-Type: application/json

{
    "nameForm": "formulario 1 actualizado correctamente",
    "nameUser": "Juan",
    "lastnameone": "Perez",
    "lastnametwo": "Sanchez",
    "birthday": "20 de noviembre",
    "category1": "infantil SC",
    "typekit": "Kit asociacion",
    "talla": "M",
    "team": "garzas",
    "phone": "1234567890",
    "email": "leo@gmail.com",
    "origin": "Teotihuacan"
}

###
/// Eliminar formulario
DELETE http://localhost:5000/forms/8225ec4d-f2a2-45b5-9b30-c81c58833d54

###